# Generated by Django 5.1 on 2024-09-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('requires_exam', models.BooleanField()),
                ('tuition_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_half_acceptances', models.IntegerField()),
                ('second_half_acceptances', models.IntegerField()),
                ('women', models.CharField(max_length=50)),
                ('men', models.CharField(max_length=50)),
                ('extra_information', models.TextField()),
                ('field_of_study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='komak_reshte.fieldofstudy')),
            ],
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komak_reshte.university'),
        ),
    ]
